const VMP = {

    //FISICO-QUIMICO
    pH_MIN: 6.5,
    pH_MAX: 8.5,
    NIVEL_AGUA_MIN: 1,
    NIVEL_AGUA_MAX: 10,
    TEMPERATURA_MIN: 2,
    TEMPERATURA_MAX: 30,
    TURBIDEZ_MIN: 0.5,
    TURBIDEZ_MAX: 5,
    CONDUTIVIDADE_MIN: 50,
    CONDUTIVIDADE_MAX: 200

    // ALCALINIDADE: 400.00,
    // CONDUTIVIDADE_MIN: 50,
    // CONDUTIVIDADE_MAX: 1500,
    // DUREZA_TOTAL: 500.00,

    //QUIMICO
    // FERRO: 0.3,
    // MANGANÊS: 0.1,
    // CLORETO: 250.00,
    // COBRE: 2,
    // ZINCO: 5,
    // SULFATOS: 250.00,

}

module.exports = VMP